name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:

      - name: Deploy to Server
        uses: appleboy/ssh-action@master #ssh 연결을 위한 action
        with:
            host: ${{ secrets.PI_HOST }}
            username: ${{ secrets.PI_USERNAME }}
            key: ${{ secrets.PI_KEY }}
            script_stop: true #스크립트 실행중 오류 발생시 중단
            script: |
              cd spring_project/GongGuBox-Backend/ 
              git pull
              ./buildxtest
              ./reboot
              

